### ISSUE TITLE
Enable latex processing of RS proposals and reports

### ISSUE THREAD

**Issue by dtabell** [radiasoft/container-beamsim-jupyter-base#56]
On attempting to compile [this project progress report](https://github.com/radiasoft/prop20_silas/tree/master/reports/phase_2_3month) on our Jupyter server, I received many complaints about missing packages. It would be great if the installation of latex on Jupyter could build all proposals and reports. Most any recent proposal will also work as a test. [This one](https://github.com/radiasoft/prop20_blicon/tree/master/phase_2/narrative), for example.

**Comment by bruhwiler** [comment]
I believe we had a full LaTex installation in the beams image at one time, but not for quite a while.
IIRC, the problem is that it takes something close to a GB of space, which bloats the image.

I think this issues requires some thought as to whether a complete LaTex installation provides enough benefit to enough users.

**Comment by dtabell** [comment]
It might suffice to install the medium distro and add a few extra packages
“by hand”.

**Comment by robnagler** [comment]
@dtabell if you figure out what packages are needed, we can add them to the install. Not sure it's best use of @e-carlin's time to figure out how to run latex. 

We do install texlive-scheme-medium, which should have quite a few packages already installed.
